name: C/C++ CI

on:
  push:

jobs:
  my_job:
    name: compile
    runs-on: ubuntu-latest
    
    steps:
    - name: Compile
      run: gcc main.c print_colours.c -o ./shell
    - name: Run shell
      run: ./shell
